version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proto-app
    env_file:
      - .env
    networks:
      - app-network
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
